# Generated by Django 3.2.7 on 2021-10-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimg',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_img', models.ImageField(upload_to='testimg/')),
            ],
        ),
    ]
