# Generated by Django 3.2.7 on 2021-10-21 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_firform'),
    ]

    operations = [
        migrations.AddField(
            model_name='firform',
            name='Officer_Name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='records.userauth'),
        ),
    ]
